### ISSUE TITLE
Push to NPM

### ISSUE THREAD

**Issue by Karankang007** [martinroob/tiny-translator#30]
Can you please publish this project as an NPM package without the docker folder?

This will be useful for projects which want to use xliffmerge tool and provide a default editor.

**Comment by martinroob** [comment]
Hello,
I' m not sure if I understand your request.
tiny-translator is not a library or a command line tool, but a webapp that runs in the browser.
So what should I publish to npm?
There is a demo installation on github pages, so you just have to click the link to start it.
Maybe you can explain your needs a little bit further.

**Comment by quanterion** [comment]
I can think of publishing tiny-translator as Angular component (just like Material components) that users can install and insert into their app. When it will be possible to configure it so this component loads xlf automatically. It can create a great workflow: users generate a new xlf file, run their app, and immediately see and translate all new words!

**Comment by martinroob** [comment]
You are right. In general it should become much more modular to allow internal usage scenarios.
But at the moment the whole i18n workflow of angular is not really modular and open.
Let us see what the future will bring...

**Comment by quanterion** [comment]
In 5.0 NG team promises to simplify library publishing and in 5.x I hope they introduce text translations in source files
