### ISSUE TITLE
feat: add keyboard shortcut for the next button

### ISSUE THREAD

**Issue by quanterion** [martinroob/tiny-translator#40]
First of all many thanks for a great work you have done in this project!
It would be cool if I can translate items one by one without touching mouse.
So I propose to add a shortcut for the "Next" button. I.e Ctrl+Enter. So pressing this shortcut while  translation input is active accepts current translation and goes to the next item.

**Comment by martinroob** [comment]
Looks great.
Will incorporate your pull request as soon as possible (hopefully tomorrow).
Thanks for your contribution.

In fact adding some keyboard accessability features is on the Todo List.

**Comment by martinroob** [comment]
integrated in v0.9
