### ISSUE TITLE
Cannot find module 'rxjs/observable'

### ISSUE THREAD

**Issue by skormel** [martinroob/tiny-translator#43]
When I try to run tiny-translator with **npm run start-en** I always get the error:

`ERROR in /bla/bla/bla/tiny-translator/src/app/app.component.ts (5,26): Cannot find module 'rxjs/observable'.`

So I modified **app.component.ts** with this code:

`import {Observable} from "rxjs/Observable";  //Observable must be capitalized not in lowercase.`

Best Regards,
Antonio.

**Comment by martinroob** [comment]
You are absolutely right.
It is a typo.
I'm using Windows,  so I never saw this error.
Will correct it soon.
