### ISSUE TITLE
Technology Update to Angular 5 etc.

### ISSUE THREAD

**Issue by martinroob** [martinroob/tiny-translator#44]
Update dependencies (angular, material, ..) to current versions.

**Comment by AntonisFK** [comment]
If you are getting this error after running  npm run start `ERROR in node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10): error TS2305: Module '"coding/help/tiny-translator/node_modules/@angular/core/core"' has no exported member 'OpaqueToken'.`.  Look at this pull request, it will fix that issue https://github.com/martinroob/tiny-translator/pull/49.

**Comment by martinroob** [comment]
Done with v0.13 (upgrade to Angular 7)
