### ISSUE TITLE
Are translation states supported in XMB/XTB?

### ISSUE THREAD

**Issue by akrueger** [martinroob/tiny-translator#50]
I am using XMB/XTB and the app is showing me some "untranslated" ids that I can't seem to mark as translated. This mainly seems to happen when the translation is identical (a phone number for instance). If I change the translation to something different, it appears to work.

I can understand the logic of this not being considered a translatable field if the values are the same, but in the case of many localizations, there are times where the value will stay the same in some translations and change in others (Arabic numerals are another example).

I know that this was an attribute on XLF files, but I don't see anywhere for it in the XTB. 

So I suppose the question is:

1) Does XMB/XTB support translation states
2) If not, is there a way to disable it in the app?

Thanks for your work!

**Comment by martinroob** [comment]
In fact XMB/XTB does not  support translation states. 
The library underneath Tiny translator assumes state "new" if source and target are identical,  otherwise it assumes "final".

**Comment by akrueger** [comment]
Ok, good to know that it's part of TinyTranslator rather than the interchange format.

Thanks!
